/*
  COMPUTER OPPONENT DATA for Twenty Questions Duel
  =================================================
  For each category: the yes/no question menu (q) and every item's answers (a).
  Each answer string has one letter per question, in order: y = yes, n = no, s = sort of.
  Extra questions about genre, era, region and so on are built automatically from each
  item's tags and year (see AUTOQ at the bottom), so they never need answers here.

  When you add an item to catalog.js, add its answer string here too (same name).
  Items without answers still work in games with friends; they are just left out of
  computer games until they have them. Run  node check-catalog.js  to see what's missing.
*/
window.BOT = {
  Celebrities: {
    q: [
      ["woman", "Is this person a woman?"],
      ["american", "Is this person American?"],
      ["british", "Is this person British?"],
      ["alive", "Is this person still alive?"],
      ["died_before_2000", "Did this person die before the year 2000?"],
      ["born_before_1960", "Was this person born before 1960?"],
      ["born_before_1980", "Was this person born before 1980?"],
      ["team_sport", "Are they famous for playing a team sport?"],
      ["ball_sport", "Is their sport played with a ball?"],
      ["basketball", "Are they a basketball player?"],
      ["outdoor_sport", "Is their sport usually played outdoors?"],
      ["olympian", "Have they competed in the Olympics?"],
      ["ny_la_team", "Have they played for a New York or Los Angeles team?"],
      ["oscar", "Have they won an Oscar?"],
      ["grammy", "Have they won a Grammy?"],
      ["band", "Did they become famous as part of a band or group?"],
      ["comedian", "Are they mainly known for comedy?"],
      ["superhero", "Have they appeared in a superhero movie?"],
      ["action", "Are they known for action movies?"],
      ["sitcom", "Did they star in a TV sitcom?"],
      ["halftime", "Have they headlined a Super Bowl halftime show?"],
      ["instrument", "Are they famous for playing an instrument?"],
      ["songwriter", "Do they write their own songs?"],
      ["biopic", "Has a movie been made about their life?"],
      ["one_name", "Do they go by just one name?"],
      ["famous_young", "Did they become famous as a child or teenager?"]
    ],
    a: {
      "Taylor Swift": "yynynnnnnnnnnnynnnnnnsynny",
      "Beyoncé": "yynynnnnnnnnnnyynnnnynynyy",
      "Oprah Winfrey": "yynynyynnnnnnsnnnnnnnnnnnn",
      "Tom Hanks": "nynynyynnnnnnynnnnnnnnnnnn",
      "Michael Jordan": "nynynnyyyynynnnnnnnnnnnnnn",
      "Serena Williams": "yynynnnnynyynnnnnnnnnnnsny",
      "Elvis Presley": "nynnyyynnnnnnnynnnnnnnnynn",
      "Marilyn Monroe": "yynnyyynnnnnnnnnnnnnnnnynn",
      "Leonardo DiCaprio": "nynynnynnnnnnynnnnnnnnnnny",
      "Dwayne Johnson": "nynynnyssnsnnnnnnyynnnnnnn",
      "Lady Gaga": "yynynnnnnnnnnyynnynnynynnn",
      "Michael Jackson": "nynnnyynnnnnnnyynnnnynyyny",
      "Lionel Messi": "nnnynnnyynyynnnnnnnnnnnnns",
      "Rihanna": "ynnynnnnnnnnnnynnnnnynnnyy",
      "Keanu Reeves": "nnnynnynnnnnnnnnnsynnnnnnn",
      "Simone Biles": "yynynnnnnnnynnnnnnnnnnnnny",
      "Usain Bolt": "nnnynnnnnnyynnnnnnnnnnnnnn",
      "Muhammad Ali": "nynnnyynnnnynnnnnnnnnnnynn",
      "Dolly Parton": "yynynyynnnnnnnynnnnnnsynnn",
      "LeBron James": "nynynnnyyynyynnnnnnnnnnnny",
      "Ed Sheeran": "nnyynnnnnnnnnnynnnnnnyynnn",
      "Billie Eilish": "yynynnnnnnnnnyynnnnnnnynny",
      "Bruno Mars": "nynynnnnnnnnnnysnnnnyyynnn",
      "Ariana Grande": "yynynnnnnnnnnnynnnnynnynny",
      "Freddie Mercury": "nnynyyynnnnnnnsynnnnnsyynn",
      "Frank Sinatra": "nynnyyynnnnnnyysnnnnnnnnnn",
      "Madonna": "yynynyynnnnnnnynnnnnynynyn",
      "Drake": "nnnynnnnnnnnnnynnnnnnnynyy",
      "Will Smith": "nynynnynnnnnnyyynyyynnsnnn",
      "Meryl Streep": "yynynyynnnnnnynnnnnnnnnnnn",
      "Zendaya": "yynynnnnnnnnnnnnnynynnnnyy",
      "Robert Downey Jr.": "nynynnynnnnnnynnnyynnnnnnn",
      "Morgan Freeman": "nynynyynnnnnnynnnynnnnnnnn",
      "Jackie Chan": "nnnynyynnnnnnsnnsnynnnnnnn",
      "Charlie Chaplin": "nnynyyynnnnnnynnynnnnnnynn",
      "Tom Brady": "nynynnyyynynnnnnnnnnnnnnnn",
      "Tiger Woods": "nynynnynynynnnnnnnnnnnnnny",
      "Cristiano Ronaldo": "nnnynnnyynyynnnnnnnnnnnnns",
      "Wayne Gretzky": "nnnynnyynnnyynnnnnnnnnnnny",
      "Babe Ruth": "nynnyyyyynynynnnnnnnnnnynn",
      "Whitney Houston": "yynnnnynnnnnnnynnnnnnnnynn",
      "Elton John": "nnyynyynnnnnnyynnnnnnyyynn",
      "Prince": "nynnnyynnnnnnyysnnnnyyynyn",
      "John Lennon": "nnynyyynnnnnnsyynnnnnyyynn",
      "Bob Marley": "nnnnyyynnnnnnnsynnnnnyyynn",
      "Aretha Franklin": "yynnnyynnnnnnnynnnnnnnsynn",
      "Stevie Wonder": "nynynyynnnnnnnynnnnnyyynny",
      "Justin Bieber": "nnnynnnnnnnnnnynnnnnnnsnny",
      "Adele": "ynyynnnnnnnnnnynnnnnnnynyn",
      "Johnny Cash": "nynnnyynnnnnnnynnnnnnyyynn",
      "Mariah Carey": "yynynnynnnnnnnynnnnnnnynnn",
      "Shakira": "ynnynnynnnnnnnynnnnnynynyn",
      "Louis Armstrong": "nynnyyynnnnnnnynnnnnnynnnn",
      "Jennifer Aniston": "yynynnynnnnnnnnnsnnynnnnnn",
      "Brad Pitt": "nynynnynnnnnnynnnssnnnnnnn",
      "Tom Cruise": "nynynnynnnnnnnnnnnynnnnnnn",
      "Audrey Hepburn": "ynsnyyynnnnnnynnnnnnnnnnnn",
      "Denzel Washington": "nynynyynnnnnnynnnnynnnnnnn",
      "Jim Carrey": "nsnynnynnnnnnnnnyynnnnnnnn",
      "Ellen DeGeneres": "yynynyynnnnnnnnnynnynnnnnn",
      "Robin Williams": "nynnnyynnnnnnyynynnynnnnnn",
      "Julia Roberts": "yynynnynnnnnnynnnnnnnnnnnn",
      "Scarlett Johansson": "yynynnnnnnnnnnnnnyynnnnnny",
      "Lucille Ball": "yynnyyynnnnnnnnnynnynnnynn",
      "Harrison Ford": "nynynyynnnnnnnnnnyynnnnnnn",
      "Kevin Hart": "nynynnynnnnnnnnnynnsnnnnnn",
      "Sandra Bullock": "yynynnynnnnnnynnnnsnnnnnnn",
      "Kobe Bryant": "nynnnnyyyynyyynnnnnnnnnnny",
      "Stephen Curry": "nynynnnyyynynnnnnnnnnnnnnn",
      "Pelé": "nnnnnyyyynynynnnnnnnnnnnyy",
      "Jackie Robinson": "nynnyyyyynynynnnnnnnnnnynn",
      "Michael Phelps": "nynynnnnnnnynnnnnnnnnnnnny",
      "Shaquille O'Neal": "nynynnyyyynyynnnnynnnnnnnn",
      "Patrick Mahomes": "nynynnnyynynnnnnnnnnnnnnnn",
      "Mia Hamm": "yynynnyyynyynnnnnnnnnnnnnn",
      "Roger Federer": "nnnynnnnynyynnnnnnnnnnnnnn",
      "Shohei Ohtani": "nnnynnnyynynynnnnnnnnnnnnn",
      "Caitlin Clark": "yynynnnyyynnnnnnnnnnnnnnnn",
      "Jesse Owens": "nynnyyynnnyynnnnnnnnnnnynn",
      "Derek Jeter": "nynynnyyynynynnnnnnnnnnnnn"
    }
  },
  Places: {
    q: [
      ["usa", "Is it in the United States?"],
      ["ocean", "Is it on or right next to the ocean or sea?"],
      ["water_body", "Is it a body of water or a waterfall?"],
      ["mountain", "Is it a mountain, or high up in the mountains?"],
      ["inside", "Is it a building you can go inside?"],
      ["religious", "Is it a religious or sacred site?"],
      ["old1000", "Is it more than 1,000 years old?"],
      ["capital", "Is it in a country's capital city?"],
      ["island", "Is it an island or a group of islands?"],
      ["south", "Is it in the Southern Hemisphere?"],
      ["desert", "Is it in a desert?"],
      ["lights", "Is it famous for its lights at night?"],
      ["tall", "Is it a tall tower or statue?"],
      ["ruins", "Is it ancient ruins?"],
      ["english", "Is English the main language spoken there?"],
      ["modern", "Was it built in the 1900s or later?"],
      ["border", "Does it cross or sit on a border between countries?"],
      ["big_city", "Is it in or part of a big city?"],
      ["tropical", "Does it have a tropical climate?"],
      ["wildlife", "Is it famous for its wild animals?"],
      ["mediterranean", "Is it in a country on the Mediterranean Sea?"],
      ["east_asia", "Is it in China or Japan?"],
      ["ruler", "Was it built for a king, emperor, or pharaoh?"],
      ["spanish_port", "Do people there mainly speak Spanish or Portuguese?"],
      ["huge", "Does it stretch for hundreds of miles?"],
      ["aus_nz", "Is it in Australia or New Zealand?"]
    ],
    a: {
      "Eiffel Tower": "nnnnsnnynnnyynnnnynnynnnnn",
      "Statue of Liberty": "yynnsnnnsnnnynynnynnnnnnnn",
      "Grand Canyon": "ynnnnnynnnsnnnynnnnnnnnnyn",
      "Great Wall of China": "nnnsnnysnnsnnsnnnnnnnysnyn",
      "Mount Everest": "nnnynnynnnnnnnnnynnnnsnnnn",
      "Taj Mahal": "nnnnysnnnnnnnnnnnynnnnynnn",
      "Colosseum": "nnnnsnyynnnnnynnnynnynsnnn",
      "Machu Picchu": "nnnynnnnnynnnynnnnsnnnsynn",
      "Niagara Falls": "snynnnynnnnnnnynynnnnnnnnn",
      "Sydney Opera House": "nynnynnnnynsnnyynynnnnnnny",
      "Stonehenge": "nnnnnsynnnnnnyynnnnnnnnnnn",
      "Golden Gate Bridge": "yynnnnnnnnnnnnyynynnnnnnnn",
      "Great Pyramid of Giza": "nnnnssysnnynnsnnnsnnynynnn",
      "Venice": "nynnnnynynnnnnnnnsnnynnnnn",
      "Las Vegas": "ynnnnnnnnnyynnyynynnnnnnnn",
      "Antarctica": "nynnnnynnysnnnsnnnnynnnnyn",
      "Mount Rushmore": "ynnsnnnnnnnnsnyynnnnnnnnnn",
      "Big Ben": "nnnnsnnynnnnynynnynnnnnnnn",
      "Great Barrier Reef": "nysnnnynnynnnnynnnyynnnnyy",
      "Hollywood Sign": "ynnynnnnnnnnnnyynynnnnnnnn",
      "Christ the Redeemer": "nsnynynnnynnynnynyynnnnynn",
      "Iguazu Falls": "nnynnnynnynnnnnnynsnnnnynn",
      "Galápagos Islands": "nynnnnynysnnnnnnnnsynnnynn",
      "Easter Island": "nynnnssnyynnnsnnnnsnnnnynn",
      "Victoria Falls": "nnynnnynnynnnnynynsnnnnnnn",
      "Mount Kilimanjaro": "nnnynnynnynnnnnnnnssnnnnnn",
      "Sahara": "nsnnnnynnnynnnnnynnnsnnnyn",
      "Cape Town": "nynsnnnsnynnnnsnnynnnnnnnn",
      "Tokyo": "nynnnnnynnnynnnnnynnnynnnn",
      "Dubai": "nynnnnnnnnysnnnsnynnnnnnnn",
      "Petra": "nnnsnsynnnynnynnnnnnnnsnnn",
      "Angkor Wat": "nnnnyynnnnnnnsnnnnynnnsnnn",
      "Mount Fuji": "nnnynsynnnnnnnnnnnnnnynnnn",
      "New York City": "yynnnnnnsnnsnnynnynnnnnnnn",
      "Yellowstone National Park": "ynnsnnynnnnnnnynnnnynnnnsn",
      "London": "nnnnnnyynnnnnnynnynnnnnnnn",
      "Leaning Tower of Pisa": "nnnnsnnnnnnnynnnnnnnynnnnn",
      "Parthenon": "nnnsnyyynnnnnynnnynnynnnnn",
      "Uluru": "nnnsnyynnyynnnynnnnnnnnnny",
      "Hawaii": "yynsnnynynnnnnynnnynnnnnsn",
      "Chichen Itza": "nnnnnyynnnnnnynnnnynnnnynn",
      "Space Needle": "ynnnynnnnnnnynyynynnnnnnnn",
      "Alcatraz Island": "yynnynnnynnnnnysnsnnnnnnnn",
      "Times Square": "ynnnnnnnnnnynnysnynnnnnnnn",
      "Chicago": "ynnnnnnnnnnnnnynnynnnnnnnn",
      "New Orleans": "ysnnnnnnnnnnnnynnssnnnnnnn",
      "Death Valley": "ynnnnnynnnynnnynnnnnnnnnsn",
      "Paris": "nnnnnnyynnnynnnnnynnynnnnn",
      "Rome": "nnnnnsyynnnnnsnnnynnynnnnn",
      "Amsterdam": "nsnnnnnynnnnnnnnnynnnnnnnn",
      "Neuschwanstein Castle": "nnnyynnnnnnnnnnnnnnnnnynnn",
      "Sagrada Família": "nnnnyynnnnnnnnnsnynnynnynn",
      "Matterhorn": "nnnynnynnnnnnnnnynnnsnnnnn",
      "Cliffs of Moher": "nynnnnynnnnnnnynnnnnnnnnnn",
      "Hong Kong": "nynnnnnnsnnynnsnnysnnynnnn",
      "Singapore": "nynnnnnyynnsnnsnnyynnnnnnn",
      "Bali": "nynnnsnnyynnnnnnnnynnnnnnn",
      "Burj Khalifa": "nnnnynnnnnysynnynynnnnnnnn",
      "Forbidden City": "nnnnynnynnnnnnnnnynnnyynnn",
      "Ha Long Bay": "nyynnnynsnnnnnnnnnsnnnnnnn",
      "Dead Sea": "nnynnnynnnynnnnnynnnsnnnnn",
      "Gobi Desert": "nnnnnnynnnynnnnnynnsnynnyn",
      "Rio de Janeiro": "nynsnnnnnynnnnnnnyynnnnynn",
      "Nazca Lines": "nnnnnnynnyynnsnnnnnnnnnynn",
      "Amazon Rainforest": "nnnnnnynnynnnnnnynyynnnyyn",
      "Angel Falls": "nnysnnynnnnnnnnnnnynnnnynn",
      "Atacama Desert": "nsnnnnynnyynnnnnnnnnnnnyyn",
      "Lake Titicaca": "nnyynnynnynnnnnnynnnnnnynn",
      "Melbourne": "nynnnnnnnynnnnynnynnnnnnny",
      "Tasmania": "nynnnnynyynnnnynnnnsnnnnny",
      "Sydney Harbour Bridge": "nynnnnnnnynsnnyynynnnnnnny",
      "Hobbiton Movie Set": "nnnnsnnnnynnnnyynnnnnnnnny",
      "Milford Sound": "nyysnnynnynnnnynnnnnnnnnny",
      "Bora Bora": "nynnnnynyynnnnnnnnynnnnnnn",
      "Cairo": "nnnnnnyynnynnnnnnynnynnnnn",
      "Marrakesh": "nnnnnnsnnnsnnnnnnsnnynnnnn",
      "Great Sphinx": "nnnnnsysnnynysnnnsnnynynnn",
      "Abu Simbel": "nnnnyyynnnynnnnnnnnnynynnn",
      "Serengeti": "nnnnnnynnynnnnsnnnyynnnnsn",
      "Nile": "nnynnnynnssnnnnnysnnynnnyn"
    }
  },
  Movies: {
    q: [
      ["disney_pixar", "Is it a Disney or Pixar movie?"],
      ["franchise", "Is it part of a franchise or did it get sequels?"],
      ["book", "Is it based on a book?"],
      ["true_story", "Is it based on real events or real people?"],
      ["space", "Is much of it set in outer space or on another planet?"],
      ["magic", "Is there magic in it?"],
      ["talking_animal", "Is a talking animal a main character?"],
      ["best_picture", "Did it win the Oscar for Best Picture?"],
      ["musical", "Is it a musical where characters break into song?"],
      ["rated_r", "Is it rated R?"],
      ["future_time", "Is it set in the future or does it involve time travel?"],
      ["kid_teen", "Is the main character a kid or a teenager?"],
      ["robots", "Are there robots, androids, or cyborgs in it?"],
      ["usa", "Is it set mostly in the United States?"],
      ["sea", "Is much of it set at sea or underwater?"],
      ["romance", "Is a romance at the center of the story?"],
      ["spielberg_nolan", "Was it directed by Steven Spielberg or Christopher Nolan?"],
      ["monster_villain", "Is the villain a monster, creature, or alien?"],
      ["military", "Is war or the military a big part of it?"],
      ["holiday", "Does it take place around a holiday?"],
      ["school", "Does much of it take place at a school?"],
      ["royalty", "Is a main character a king, queen, prince, or princess?"],
      ["aliens", "Are there aliens in it?"],
      ["computer_animated", "Is it computer-animated?"],
      ["name_in_title", "Does the title include a character's name?"],
      ["female_lead", "Is the main character female?"],
      ["nonhuman_lead", "Is the main character not a human?"]
    ],
    a: {
      "The Godfather": "nyynnnnynynnnynnnnnnnnnnnnn",
      "Titanic": "nnnynnnynnnnnnyynnnnnnnnnyn",
      "Jurassic Park": "nyynnnnnnnnnnnnnyynnnnnnnnn",
      "Star Wars": "nynnysnnnnnnynnnnnynnnynnnn",
      "The Lion King": "yynnnnynynnsnnnnnnnnnynnnny",
      "Jaws": "nyynnnnnnnnnnyynyynynnnnnnn",
      "Frozen": "yynnnynnynnnnnnnnnnnnynynyn",
      "Toy Story": "yynnnnnnnnnnnynnnnnnnnsynny",
      "The Wizard of Oz": "nsynnyynynnysnnnnnnnnnnnsyn",
      "The Dark Knight": "nynnnnnnnnnnnynnynnnnnnnnnn",
      "Forrest Gump": "nnynnnnynnnnnynsnnynnnnnynn",
      "The Matrix": "nynnnnnnnyynssnnnnnnnnnnnnn",
      "Back to the Future": "nynnnnnnnnyynynnnnnnnnnnnnn",
      "E.T. the Extra-Terrestrial": "nnnnnnnnnnnynynnynnnnnynyns",
      "Finding Nemo": "yynnnnynnnnsnnynnnnnnnnyyny",
      "Home Alone": "nynnnnnnnnnynynnnnnynnnnnnn",
      "Shrek": "nyynnyynnnnnnnnynnnnnynyyny",
      "The Shawshank Redemption": "nnynnnnnnynnnynnnnnnnnnnnnn",
      "Barbie": "nsnnnsnnsnnnnsnnnnnnnnnnyyn",
      "Spirited Away": "nnnnnynnnnnynnnnnnnnnnnnnyn",
      "Raiders of the Lost Ark": "nynnnnnnnnnnnnnnynsnnnnnnnn",
      "The Breakfast Club": "nnnnnnnnnynynynnnnnnynnnnnn",
      "Ghostbusters": "nynnnsnnnnnnnynnnynnnnnnnnn",
      "The Terminator": "nynnnnnnnyynyynnnnsnnnnnnns",
      "Top Gun": "nynnnnnnnnnnnynsnnynsnnnnnn",
      "Avengers: Endgame": "synnsnnnnnynssnnnysnnnynnnn",
      "Inception": "nnnnnnnnnnnnnnnnynnnnnnnnnn",
      "Coco": "ynnnnnnnynnynnnnnnnynnnyynn",
      "Black Panther": "synnnnnnnnnnnnnnnnnnnynnnnn",
      "Oppenheimer": "nnyynnnynynnnynnynynnnnnynn",
      "Get Out": "nnnnnnnnnynnnynnnnnnnnnnnnn",
      "Inside Out": "yynnnnnnnnnynynnnnnnnnnynyy",
      "Harry Potter and the Sorcerer's Stone": "nyynnynnnnnynnnnnnnnynnnynn",
      "Pirates of the Caribbean": "yynnnynnnnnnnnynnnnnnnnnnnn",
      "Up": "ynnnnnynnnnnnsnnnnnnnnnynnn",
      "Mean Girls": "nsynnnnnnnnynynnnnnnynnnnyn",
      "The Lord of the Rings: The Fellowship of the Ring": "nyynnynnnnnnnnnnnysnnsnnnnn",
      "Psycho": "nyynnnnnnynnnynnnnnnnnnnnsn",
      "Grease": "nynnnnnnynnynynynnnnynnnnsn",
      "Rocky": "nynnnnnynnnnnynnnnnnnnnnynn",
      "Casablanca": "nnnnnnnynnnnnnnynnynnnnnnnn",
      "Snow White and the Seven Dwarfs": "ynsnnynnynnsnnnsnnnnnynnyyn",
      "Alien": "nynnynnnnyynynnnnynnnnynnyn",
      "Singin' in the Rain": "nnnnnnnnynnnnynynnnnnnnnnnn",
      "The Sound of Music": "nnsynnnyynnnnnnynnsnnnnnnyn",
      "Cinderella": "yysnnyynynnnnnnynnnnnsnnyyn",
      "Some Like It Hot": "nnnnnnnnnnnnnynsnnnnnnnnnnn",
      "It's a Wonderful Life": "nnsnnnnnnnnnnynsnnnynnnnnnn",
      "The Empire Strikes Back": "nynnysnnnnnnynnnnnynnnynnnn",
      "Ferris Bueller's Day Off": "nnnnnnnnnnnynynnnnnnsnnnynn",
      "Die Hard": "nyynnnnnnynnnynnnnnynnnnnnn",
      "The Little Mermaid": "yysnnyynynnynnyynsnnnynnnyn",
      "Beetlejuice": "nynnnsnnnnnnnynnnsnnnnnnynn",
      "Rain Man": "nnnnnnnynynnnynnnnnnnnnnsnn",
      "The Princess Bride": "nnynnsnnnnnnnnnynnnnnynnnnn",
      "Dead Poets Society": "nnnnnnnnnnnynynnnnnnynnnnnn",
      "Beauty and the Beast": "yssnnynnynnnnnnynnnnnynnnyn",
      "Aladdin": "yysnnyynynnnnnnynnnnnynnynn",
      "Men in Black": "nynnnnnnnnnnnynnnynnnnynnnn",
      "Independence Day": "nynnsnnnnnnnnynnnyyynnynnnn",
      "Groundhog Day": "nnnnnsnnnnsnnynsnnnynnnnnnn",
      "Mrs. Doubtfire": "nnynnnnnnnnnnynnnnnnnnnnynn",
      "Good Will Hunting": "nnnnnnnnnynnnynnnnnnsnnnynn",
      "Apollo 13": "nnyyynnnnnnnnsnnnnnnnnnnnnn",
      "Monsters, Inc.": "yynnnnnnnnnnnnnnnsnnnnnynny",
      "The Incredibles": "yynnnnnnnnnsysnnnnnnnnnynnn",
      "Elf": "nnnnnsnnsnnnnynnnnnynnnnnnn",
      "School of Rock": "nnnnnnnnsnnnnynnnnnnynnnnnn",
      "Gladiator": "nynsnnnynynnnnnnnnynnsnnnnn",
      "Avatar": "nynnynnnnnynnnnsnnynnnysnns",
      "The Pursuit of Happyness": "nnyynnnnnnnnnynnnnnnnnnnnnn",
      "Ratatouille": "ynnnnnynnnnnnnnnnnnnnnnynny",
      "Moana": "yynnnynnynnynnynnnnnnsnyyyn",
      "Encanto": "ynnnnynnynnynnnnnnnnnnnynyn",
      "Mad Max: Fury Road": "nynnnnnnnyynnnnnnnnnnnnnysn",
      "Interstellar": "nnnnynnnnnynysnnynnnnnnnnnn",
      "La La Land": "nnnnnnnnynnnnynynnnnnnnnnsn",
      "The Social Network": "nnyynnnnnnnnnynnnnnnsnnnnnn",
      "Crazy Rich Asians": "nnynnnnnnnnnnnnynnnnnnnnnyn",
      "Top Gun: Maverick": "nynnnnnnnnnnnynnnnynnnnnynn"
    }
  },
  Songs: {
    q: [
      ["female", "Is the lead singer a woman?"],
      ["band", "Is it by a band or group (not a solo artist)?"],
      ["american", "Is the artist American?"],
      ["british", "Is the artist British?"],
      ["love", "Is it a love song?"],
      ["dance", "Is it mainly a dance or party song?"],
      ["ballad", "Is it a slow ballad?"],
      ["no1_us", "Did it reach No. 1 on the US charts?"],
      ["collab", "Is it a collaboration or does it feature a guest artist?"],
      ["non_english", "Is it sung at least partly in a language other than English?"],
      ["one_word", "Is the title just one word?"],
      ["long_title", "Does the title have four or more words?"],
      ["name_title", "Does the title include the name of a person or place?"],
      ["pronoun_title", "Does the title contain the word \"I\", \"my\", or \"you\"?"],
      ["movie", "Was it written for, or made famous by, a movie?"],
      ["heartbreak", "Is it about a breakup or heartbreak?"],
      ["video", "Is its music video especially famous?"],
      ["dance_move", "Is it known for a famous dance or dance move?"],
      ["long_song", "Is it famously long (over five minutes)?"],
      ["guitar", "Is it known for a famous guitar riff or solo?"],
      ["social", "Does it carry a social or political message?"],
      ["rap", "Does it include rapping?"],
      ["one_name", "Does the artist go by a single name?"],
      ["title_track", "Is it the title track of an album?"]
    ],
    a: {
      "Bohemian Rhapsody": "nynynnsnnnnnnnsnnnysnnnn",
      "Billie Jean": "nnynnynynnnnynnnsynnnnnn",
      "Hey Jude": "nynysnyynnnnynnnnnynnnnn",
      "Imagine": "nnnynnynnnynnnnnnnnnynny",
      "Smells Like Teen Spirit": "nyynnnnnnnnynnnnynsynnnn",
      "Hotel California": "nyynnnnynnnnynnnnnyynnny",
      "Thriller": "nnynnsnnnnynnnnnyysnnnny",
      "Sweet Child o' Mine": "nyynynnynnnynnnnnnsynnnn",
      "Stairway to Heaven": "nynynnsnnnnnnnnnnnyynnnn",
      "Purple Rain": "nsynsnynnnnnnnynnnynnnyy",
      "Respect": "ynynnnnynnynnnnnnnnnsnnn",
      "Rolling in the Deep": "ynnynnnynnnynnnynnnnnnyn",
      "Shape of You": "nnnyysnynnnnnynnnnnnnnnn",
      "Uptown Funk": "nnssnynyynnnnnnnnnnnnnnn",
      "Despacito": "nnsnyynyyyynnnnnynnnnynn",
      "Old Town Road": "nnynnnnysnnnnnnnnnnnnynn",
      "Blinding Lights": "nnnnysnynnnnnnnnnnnnnnnn",
      "Dancing Queen": "nynnnynynnnnnnnnnnnnnnnn",
      "Don't Stop Believin'": "nyynnnnnnnnnnnnnnnnnnnnn",
      "Shake It Off": "ynynnynynnnnnnnnnnnnnnnn",
      "...Baby One More Time": "ynynynnynnnynnnyynnnnnny",
      "Wannabe": "yynynsnynnynnnnnsnnnnnnn",
      "I Will Always Love You": "ynynynyynnnynyyynnnnnnnn",
      "Gangsta's Paradise": "nnynnnnynnnnnnynnnnnyyyy",
      "Macarena": "nynnnynynyynnnnnnynnnnnn",
      "Livin' la Vida Loca": "nnsnnynynynynnnnnnnnnnnn",
      "Waterfalls": "yyynnnnynnynnnnnnnnnynnn",
      "Crazy in Love": "ynynyynyynnnnnnnnnnnnyyn",
      "Hey Ya!": "nyynsynynnnnnnnnnnnnnnnn",
      "Umbrella": "ynnnynnyynynnnnnnnnnnyyn",
      "In da Club": "nnynnynynnnnnnnnnnnnnynn",
      "Lose Yourself": "nnynnnnynnnnnnynnnnnnyyn",
      "Mr. Brightside": "nyynnnnnnnnnnnnsnnnnnnnn",
      "Hips Don't Lie": "ynnnsynyysnnnnnnnsnnnsyn",
      "Single Ladies": "ynynnynynnnnnnnyyynnnnyn",
      "Seven Nation Army": "nyynnnnnnnnnnnnnnnnynnnn",
      "Bad Romance": "ynynyynnnnnnnnnnynnnnnnn",
      "Gangnam Style": "nnnnnynnnynnynnnyynnnyyn",
      "Happy": "nnynnynynnynnnynynnnnnnn",
      "Sweet Caroline": "nnynynnnnnnnynnnnnnnnnnn",
      "Johnny B. Goode": "nnynnnnnnnnnynsnnnnynnnn",
      "(I Can't Get No) Satisfaction": "nynynnnynnnynynnnnnynnnn",
      "Like a Rolling Stone": "nnynnnnnnnnynnnnnnynnnnn",
      "My Girl": "nyynynnynnnnnynnnnnnnnnn",
      "What's Going On": "nnynnnnnnnnnnnnnnnnnynny",
      "Superstition": "nnynnnnynnynnnnnnnnnnnnn",
      "Rapper's Delight": "nyynnynnnnnnnnnnnnynnynn",
      "Stayin' Alive": "nynsnynynnnnnnynnsnnnnnn",
      "Livin' on a Prayer": "nyynynnynnnynnnnnnnsnnnn",
      "Every Breath You Take": "nynysnnynnnynynsnnnnnnnn",
      "Back in Black": "nynnnnnnnnnnnnnnnnnynnny",
      "Like a Prayer": "ynynsnnynnnnnnnnynnnnnyy",
      "Girls Just Want to Have Fun": "ynynnynnnnnynnnnnnnnsnnn",
      "I Wanna Dance with Somebody": "ynynyynynnnynynnnnnnnnnn",
      "When Doves Cry": "nnynynnynnnnnnysnnnnnnyn",
      "The Message": "nyynnnnnnnnnnnnnnnynyyny",
      "Fight the Power": "nyynnnnnnnnnnnynnnnnyynn",
      "Wonderwall": "nynyynsnnnynnnnnnnnnnnnn",
      "Creep": "nynyynsnnnynnnnnnnnsnnnn",
      "No Diggity": "nyynsnnyynnnnnnnnnnnnynn",
      "No Scrubs": "yyynnnnynnnnnnnnnnnnnnnn",
      "Juicy": "nnynnnnnnnynnnnnnnnnnynn",
      "California Love": "nnynnnnyynnnynnnsnnnnynn",
      "Ice Ice Baby": "nnynnnnynnnnnnnnnnnnnynn",
      "My Heart Will Go On": "ynnnynyynnnynyynnnnnnnnn",
      "In the End": "nyynnnnnnnnnnnnsnnnnnynn",
      "Boulevard of Broken Dreams": "nyynnnsnnnnynnnsnnnnnnnn",
      "Yeah!": "nnynnynyynynnnnnnnnnnyyn",
      "Fallin'": "ynynynyynnynnnnnnnnnnnnn",
      "Toxic": "ynynysnnnnynnnnnynnnnnnn",
      "Since U Been Gone": "ynynnnnnnnnnnsnynnnnnnnn",
      "Gasolina": "nnsnnynnnyynnnnnnnnnnynn",
      "Gold Digger": "nnynnnnyynnnnnnnnnnnnynn",
      "Radioactive": "nyynnnnnnnynnnnnnnnnnnnn",
      "Bad Guy": "ynynnnnynnnnnnnnnnnnnnnn",
      "Leave the Door Open": "nyynynyynnnynnnnnnnnnnnn",
      "Kill Bill": "ynynnnnynnnnynnynnnnnnyn",
      "Hotline Bling": "nnnnsnnnnnnnnnnyyynnnsyn",
      "HUMBLE.": "nnynnnnynnynnnnnnnnnnynn",
      "Mi Gente": "nnnnnynnyynnnnnnnnnnnynn"
    }
  },
  Animals: {
    q: [
      ["big", "Is it bigger than a person?"],
      ["small", "Is it smaller than a house cat?"],
      ["fly", "Can it fly?"],
      ["water", "Does it spend most of its time in water?"],
      ["africa", "Does it live in the wild in Africa?"],
      ["nam", "Does it live in the wild in the US, Canada, or Mexico?"],
      ["sam", "Does it live in the wild in Central or South America?"],
      ["asia", "Does it live in the wild in Asia?"],
      ["aus", "Does it live in the wild in Australia?"],
      ["europe", "Does it live in the wild in Europe?"],
      ["meat", "Does it eat meat, fish, or insects?"],
      ["plants", "Does it eat only plants?"],
      ["pattern", "Does it have stripes or spots?"],
      ["fur", "Does it have fur?"],
      ["danger", "Is it dangerous to humans?"],
      ["noct", "Is it mostly active at night?"],
      ["cold", "Does it live in cold or polar regions?"],
      ["eggs", "Does it lay eggs?"],
      ["horns", "Does it have horns, antlers, tusks, or spines?"],
      ["trees", "Does it live in trees?"],
      ["bw", "Is it mostly black and white?"],
      ["venom", "Is it venomous or poisonous?"],
      ["legs4", "Does it walk on four legs?"],
      ["nolegs", "Does it have no legs at all?"],
      ["fish", "Is it a fish?"],
      ["color", "Is it brightly colored?"]
    ],
    a: {
      "Giraffe": "ynnnynnnnnnyyynnnnsnnnynnn",
      "Penguin": "nnnsnnnnnnynnnnnyynnynnnnn",
      "Octopus": "nsnynnnnnnynnnnsnynnnnnsns",
      "Elephant": "ynnnynnynnnynnsnnnynnnynnn",
      "Kangaroo": "snnnnnnnynnynynnnnnnnnsnnn",
      "Platypus": "nnnsnnnnynynnynynynnnyynnn",
      "Bald eagle": "nnynnynnnnynnnnnsynnnnnnnn",
      "Great white shark": "ynnynnnnnnynnnynnnnnnnnyyn",
      "Koala": "nnnnnnnnynnynynynnnynnynnn",
      "Cheetah": "nnnnynnnnnynyysnnnnnnnynnn",
      "Giant panda": "snnnnnnynnnynynnsnnnynynnn",
      "Sloth": "nnnnnnynnnnynynsnnnynnsnnn",
      "Flamingo": "nnysysynnnsnnnnnnynnnnnnny",
      "Blue whale": "ynnynnnnnnynnnnnsnnnnnnynn",
      "Chameleon": "nynnynnnnnynnnnnnynynnynns",
      "Polar bear": "ynnsnynnnnynnyynynnnnnynnn",
      "Owl": "nnynyyyyyyynnnnynynynnnnnn",
      "Axolotl": "nynynynnnnynnnnnnynnnnynny",
      "Zebra": "ynnnynnnnnnyyynnnnnnynynnn",
      "Bat": "nyynyyyyyysnnynynnnsnnnnnn",
      "Lion": "ynnnynnsnnynnyynnnnnnnynnn",
      "Tiger": "ynnnnnnynnynyyynnnnnnnynnn",
      "Gorilla": "ynnnynnnnnnynysnnnnsnnsnnn",
      "Wolf": "nnnnnynynyynnysssnnnnnynnn",
      "Camel": "ynnnynnynnnynynnnnnnnnynnn",
      "Raccoon": "nnnnnynnnnynsynynnnsnnynnn",
      "Hippopotamus": "ynnsynnnnnnynnynnnnnnnynnn",
      "Ostrich": "ynnnynnnnnnsnnsnnynnnnnnnn",
      "Peacock": "nnynnnnynnsnynnnnynnnnnnny",
      "Parrot": "nnynynyyynnsnnnnnynynnnnny",
      "Hummingbird": "nyynnyynnnnsnnnnnynnnnnnny",
      "Dolphin": "ynnynnnnnnynnnnnnnnnnnnynn",
      "Jellyfish": "nsnynnnnnnsnnnsnnsnnnynynn",
      "Sea turtle": "snnynnnnnnnsnnnnnynnnnnsnn",
      "Seahorse": "nynynnnnnnynnnnnnsnnnnnyyn",
      "Orca": "ynnynnnnnnynnnsnsnnnynnynn",
      "Komodo dragon": "snnnnnnynnynnnynnynnnyynnn",
      "Crocodile": "ynnsyyyyynynnnynnynnnnynnn",
      "Frog": "nynsyyyyyyynnnnsnynnnsynns",
      "King cobra": "snnnnnnynnynnnynnynnnynynn",
      "Moose": "ynnnnynsnsnynynnynynnnynnn",
      "Skunk": "nnnnnynnnnynyynynnnnynynnn",
      "Beaver": "nnnsnynnnynynynynnnnnnynnn",
      "Porcupine": "nnnnyyyynsnynsnynnysnnynnn",
      "Armadillo": "nsnnnyynnnynnnnynnnnnnynnn",
      "Red panda": "nsnnnnnynnnysynsnnnynnynny",
      "Meerkat": "nynnynnnnnynnynnnnnnnnynnn",
      "Rhinoceros": "ynnnynnynnnynnsnnnynnnynnn",
      "Toucan": "nnynnnynnnnsnnnnnynynnnnny",
      "Pelican": "nnysyyyyysynnnnnnynnnnnnnn",
      "Woodpecker": "nyynyyyynyynsnnnnynynnnnnn",
      "Emu": "snnnnnnnynnsnnnnnynnnnnnnn",
      "Cardinal": "nyynnynnnnnsnnnnnynynnnnny",
      "Blue jay": "nyynnynnnnnsnnnnnynynnnnny",
      "Robin": "nyynnynnnsynnnnnnynsnnnnns",
      "Puffin": "nnysnynnnyynnnnnyynnynnnns",
      "Kiwi": "nsnnnnnnnnynnnnynynnnnnnnn",
      "Swan": "nnysnynyyynynnnnnynnnnnnnn",
      "Roadrunner": "nnsnnynnnnynnnnnnynnnnnnnn",
      "Starfish": "nynynnnnnnynnnnnnsnnnnnsns",
      "Clownfish": "nynynnnnnnsnynnnnynnnnnyyy",
      "Manatee": "ynnyyyynnnnynnnnnnnnnnnynn",
      "Sea otter": "nnnynynnnnynnynnsnnnnnynnn",
      "Walrus": "ynnsnynnnnynnnsnynynnnnsnn",
      "Stingray": "snnynnnnnnynnnsnnnnnnynyyn",
      "Hammerhead shark": "snnynnnnnnynnnsnnnnnnnnyyn",
      "Lobster": "nsnynsnnnnynnnnnnynnnnnnns",
      "Narwhal": "ynnynnnnnnynsnnnynynnnnynn",
      "Pufferfish": "nsnynnnnnnynnnsnnyynnynyyn",
      "Squid": "nnnynnnnnnynnnnnnynnnnnsnn",
      "Alligator": "ynnsnynnnnynnnynnynnnnynnn",
      "Rattlesnake": "nnnnnyynnnynnnynnsnnnynynn",
      "Iguana": "nnnnnsynnnnynnnnnysynnynns",
      "Gecko": "nynnysyyynynnnnsnynnnnynnn",
      "Galápagos tortoise": "snnnnnsnnnnynnnnnynnnnynnn",
      "Salamander": "nynsnynynyynnnnsnynnnsynnn",
      "Gila monster": "nsnnnynnnnynynsnnynnnyynns",
      "Python": "ynnnynnyynynnnsnnynsnnnynn",
      "Toad": "nynnyyyyyyynnnnsnynnnsynnn",
      "Anaconda": "ynnsnnynnnynnnsnnsnnnnnynn"
    }
  },
  Foods: {
    q: [
      ["sweet", "Is it sweet?"],
      ["hot", "Is it usually served hot?"],
      ["cold", "Is it usually served cold or chilled?"],
      ["hands", "Is it usually eaten with your hands?"],
      ["meat", "Does it usually contain meat or fish?"],
      ["cheese", "Does it usually contain cheese?"],
      ["bread", "Is it a bread, or served on bread or a bun?"],
      ["pastry", "Is it a pastry?"],
      ["fried", "Is it usually fried?"],
      ["eggs", "Are eggs a main ingredient?"],
      ["produce", "Is a fruit or vegetable the main ingredient?"],
      ["spoon", "Is it usually eaten with a spoon?"],
      ["rice", "Does it contain rice?"],
      ["noodles", "Does it contain pasta or noodles?"],
      ["baked", "Is it usually baked?"],
      ["fairfood", "Is it a classic fair, ballpark, or movie theater food?"],
      ["vegetarian", "Is it usually vegetarian?"],
      ["tortilla", "Is it made with a tortilla or tortilla chips?"],
      ["potato", "Does it contain potato?"],
      ["filled", "Does it have a filling wrapped or sealed inside?"],
      ["pan", "Is it usually cooked on a griddle or in a frying pan?"],
      ["nuts", "Does it usually contain nuts?"],
      ["corn", "Is it made from corn?"],
      ["pieces", "Do you usually eat lots of small pieces of it at once?"],
      ["dip", "Is it usually dipped in a sauce or dip?"],
      ["chocolate", "Does it usually include or come with chocolate?"],
      ["bagged", "Is it commonly bought in a bag at the store?"]
    ],
    a: {
      "Pizza": "nynysysnnnnnnnynsnnnnnnnnnn",
      "Sushi": "nnssynnnnnnnynnnnnnsnnnyynn",
      "Taco": "nynyysnnsnnnnnnnsynsnnsnnnn",
      "Hamburger": "nynyysynnnnnnnnsnnnnsnnnnnn",
      "Croissant": "nsnynnsynnnnnnynynnnnnnnnnn",
      "Ramen": "nynnynnnnnnynynnnnnnnnnnnnn",
      "Pancake": "yynnnnnnnsnnnnnnynnnynnnnnn",
      "Guacamole": "nnynnnnnnnynnnnnynnnnnnnnnn",
      "Bagel": "nnnynsynnnnnnnynynnnnnnnnns",
      "Lasagna": "nynnyynnnnnnnyynsnnnnnnnnnn",
      "Burrito": "nynyysnnnnnnynnnsynynnnnnnn",
      "Hot dog": "nynyynynnnnnnnnynnnnnnnnnnn",
      "Pad thai": "nynnsnnnynnnsynnsnnnsynnnnn",
      "Apple pie": "ysnnnnnynnsnnnynynnynnnnnnn",
      "Ice cream": "ynysnnnnnnnynnnsynnnnnnnnsn",
      "Popcorn": "nsnynnnnnnnnnnnyynnnnnyynny",
      "Dumpling": "nynsynnnsnnnnnnnsnnysnnsynn",
      "Cheesecake": "ynynnynnnnnnnnynynnnnnnnnnn",
      "Waffle": "yynsnnnnnsnnnnnnynnnnnnnnnn",
      "Mac and cheese": "nynnnynnnnnsnysnynnnnnnnnnn",
      "Nachos": "nynynynnsnnnnnnysynnnnyynnn",
      "French fries": "nynynnnnynynnnnyynynnnnyynn",
      "Pretzel": "nsnynnynnnnnnnyyynnnnnnnsny",
      "Spring rolls": "nssysnnnsnnnsnnnsnnynnnnynn",
      "Chocolate chip cookie": "ynnynnnnnnnnnnynynnnnsnnsyn",
      "Tiramisu": "ynynnsnnnsnsnnnnynnnnnnnnyn",
      "Churros": "yynynnnsynnnnnnyynnnnnnnsyn",
      "Donut": "ysnynnnsynnnnnnsynnsnnnnnsn",
      "Macaron": "ynnynnnsnsnnnnynynnsnynnnnn",
      "Spaghetti": "nnnnssnnnnnnnynnsnnnnnnnnnn",
      "Quesadilla": "nynysynnnnnnnnnnsynyynsnnnn",
      "Fried chicken": "nynyynnnynnnnnnnnnnnnnnnsnn",
      "Fish and chips": "nynsynnnynnnnnnnnnynnnnnnnn",
      "Paella": "nynnynnnnnnnynnnnnnnynnnnnn",
      "Pho": "nynnynnnnnnysynnnnnnnnnnnnn",
      "Omelette": "nynnssnnnynnnnnnsnnsynnnnnn",
      "French toast": "yynnnnynyynnnnnnynnnynnnnnn",
      "Avocado toast": "nnnsnnynnssnnnnnynnnnnnnnnn",
      "Brownie": "ynnynnnnnnnnnnynynnnnsnnnyn",
      "Grilled cheese": "nynynyynnnnnnnnnynnsynnnnnn",
      "Ravioli": "nynnssnnnnnnnynnsnnynnnnnnn",
      "Risotto": "nynnnsnnnnnsynnnsnnnsnnnnnn",
      "Enchiladas": "nynnsynnnnnnnnynsynynnynnnn",
      "Fajitas": "nynyynnnnnnnnnnnnynnynnnnnn",
      "Fried rice": "nynnsnnnysnnynnnsnnnynnnnnn",
      "Meatloaf": "nynnynnnnnnnnnynnnnnnnnnnnn",
      "Chicken tikka masala": "nynnynnnnnnnsnnnnnnnnnnnnnn",
      "Tamales": "nynsssnnnnnnnnnnsnnynnynnnn",
      "Oatmeal": "nynnnnnnnnnynnnnynnnnnnnnnn",
      "Eggs Benedict": "nynnynynnynnnnnnnnnnnnnnnnn",
      "Biscuits and gravy": "nynnynynnnnnnnsnnnnnsnnnnnn",
      "Huevos rancheros": "nynnnsnnyynnnnnnyynnynynnnn",
      "Breakfast burrito": "nynyyynnnynnnnnnnyyysnnnnnn",
      "Hash browns": "nynnnnnnynynnnnnynynynnnnnn",
      "Bacon": "nynyynnnynnnnnnnnnnnynnnnnn",
      "Cinnamon roll": "ysnsnnsynnnnnnynynnnnsnnnnn",
      "Crepe": "synnssnnnsnnnnnnsnnsynnnnsn",
      "Granola": "ynnnnnnnnnnynnynynnnnynynny",
      "Potato chips": "nnnynnnnynynnnnnynynnnnysny",
      "Edamame": "nssynnnnnnynnnnnynnnnnnynns",
      "Mozzarella sticks": "nynynynnynnnnnnnynnnnnnsynn",
      "Buffalo wings": "nynyynnnynnnnnnsnnnnnnnsynn",
      "Bruschetta": "nnnynnynnnsnnnsnynnnnnnnnnn",
      "Garlic bread": "nynynsynnnnnnnynynnnnnnnnnn",
      "Beef jerky": "nnnyynnnnnnnnnnnnnnnnnnsnny",
      "Trail mix": "snnynnnnnnnnnnnnynnnnynynsy",
      "Samosa": "nsnynnnyynnnnnsnynyynnnnynn",
      "Hummus": "nnynnnnnnnsnnnnnynnnnnnnnnn",
      "Elote": "nynynynnnnynnnnsynnnnnynnnn",
      "Gelato": "ynynnnnnnnnynnnnynnnnnnnnsn",
      "Cannoli": "ynnynynyynnnnnnnynnynsnnnsn",
      "Panna cotta": "ynynnnnnnnnynnnnsnnnnnnnnnn",
      "Flan": "ynynnnnnnynynnynynnnnnnnnnn",
      "Tres leches cake": "ynynnnnnnnnsnnynynnnnnnnnnn",
      "Mochi": "ynsynnnnnnnnynnnynnynnnnnnn",
      "Crème brûlée": "ynsnnnnnnynynnynynnnnnnnnnn",
      "Banana split": "ynynnnnnnnsynnnnynnnnynnnyn",
      "S'mores": "ysnynnnnnnnnnnnnsnnnnnnnnyn",
      "Key lime pie": "ynynnnnsnnsnnnynynnnnnnnnnn",
      "Baklava": "ynnynnnynnnnnnynynnnnynnnnn"
    }
  },
  "TV Shows": {
    q: [
      ["air2024", "Was it still making new episodes in 2024?"],
      ["streaming", "Did it premiere on a streaming service or premium cable (like Netflix or HBO)?"],
      ["ten_seasons", "Did it run for 10 or more seasons?"],
      ["new_york", "Is it set in New York?"],
      ["family", "Is a family at the center of it?"],
      ["pros", "Are doctors, police, or lawyers main characters?"],
      ["audience", "Does it have a laugh track or a live studio audience?"],
      ["host", "Does it have a host?"],
      ["contestants", "Do contestants compete?"],
      ["powers", "Do characters have superpowers or magic?"],
      ["past", "Is it set in the past (when it was made)?"],
      ["foreign", "Did it start outside the US, or is it based on a foreign show?"],
      ["kids", "Are the main characters kids or teenagers?"],
      ["adapted", "Is it a spin-off, or based on a movie, book, comic, or video game?"],
      ["crime", "Is crime a big part of it?"],
      ["workplace", "Is it mostly set at a workplace?"],
      ["space", "Does it involve outer space or aliens?"],
      ["monsters", "Does it feature monsters, zombies, or ghosts?"],
      ["animal", "Is one of the main characters an animal?"],
      ["madeup", "Is it set in a made-up town or world?"],
      ["name", "Is a character's name in the title?"],
      ["hour", "Are episodes usually an hour long?"],
      ["female", "Is the main character a woman or girl?"],
      ["friends", "Is it about a group of friends?"],
      ["big_city", "Is it set in a big city?"],
      ["singing", "Is singing a big part of it?"],
      ["travel", "Do the characters travel from place to place a lot?"]
    ],
    a: {
      "Friends": "nnyynnynnnnnnnnnnnnnnnnyynn",
      "The Office": "nnnnnnnnnnnynsnynnnnnnnnnnn",
      "Breaking Bad": "nnnnssnnnnnnnnynnnnnnynnsnn",
      "Game of Thrones": "nynnynnnnysnnynnnynynynnnnn",
      "Stranger Things": "yynnsnnnnyynynnnnynynysynnn",
      "The Simpsons": "ynynynnnnnnnsnnnnnnyynnnnnn",
      "SpongeBob SquarePants": "ynynnnnnnnnnnnnsnnyyynnsnnn",
      "Seinfeld": "nnnynnynnnnnnnnnnnnnynnyynn",
      "Grey's Anatomy": "ynynnynnnnnnnnnynnnnyyynynn",
      "The Walking Dead": "nnynnsnnnnnnnynnnynnnynnnns",
      "Squid Game": "yynnnnnnynnynnnnnnnnnynnynn",
      "The Big Bang Theory": "nnynnnynnnnnnnnnnnnnnnnynnn",
      "Sesame Street": "ynysnnnnnnnnnnnnnnssnsnnyyn",
      "Survivor": "ynynnnnyynnsnnnnnnnnnynnnnn",
      "Saturday Night Live": "ynysnnyynnnnnnnnnnnnnynnyyn",
      "Wednesday": "yynnsnnnnynnyynnnynyyyynnnn",
      "The Mandalorian": "nynnnnnnnsnnnysnynnyssnnnny",
      "Bluey": "ynnnynnnnnnyynnnnnynynynsnn",
      "Star Trek": "nnnnnnnnnnnnnnnsynnynynnnny",
      "Ted Lasso": "nynnnnnnnnnsnsnynnnnysnnynn",
      "I Love Lucy": "nnnyynynnnnnnnnnnnnnynynynn",
      "The Twilight Zone": "nnnnnnnsnsnnnnnnnsnsnnnnnnn",
      "Scooby-Doo, Where Are You!": "nnnnnnynnnnnynsnnsynynnynny",
      "M*A*S*H": "nnynnyynnnynnynynnnnnnnnnnn",
      "Cheers": "nnynnnynnnnnnnnynnnnnnnsynn",
      "The Golden Girls": "nnnnnnynnnnnnnnnnnnnnnyyynn",
      "Full House": "nnnnynynnnnnsnnnnnnnnnnnynn",
      "The Fresh Prince of Bel-Air": "nnnnysynnnnnynnnnnnnnnnnysn",
      "The X-Files": "nnynnynnnsnnnnssyynnnysnnnn",
      "The Sopranos": "nynnynnnnnnnnnynnnnnyynnnnn",
      "Family Guy": "ynynynnnnnnnnnnnnnyynnnnnnn",
      "American Idol": "ynynnnyyynnynnnnnnnnnynnnyn",
      "The Amazing Race": "ynynnnnyynnnnnnnnnnnnynnnny",
      "Shark Tank": "ynynnnnnsnnynnnnnnnnnynnnnn",
      "The Great British Bake Off": "ynynnnnyynnynnnnnnnnnynnnnn",
      "Avatar: The Last Airbender": "nnnnnnnnnynnynnnnsnysnnsnny",
      "Lost": "nnnnnsnnnsnnnnnnnsnsnynnnnn",
      "Modern Family": "nnynynnnnnnnnnnnnnnnnnnnynn",
      "Rick and Morty": "ynnnynnnnnnnsnnnynnsynnnnny",
      "The Crown": "nynnynnnnnyynnnnnnnnnyynynn",
      "The Brady Bunch": "nnnnynynnnnnsnnnnnnnynnnnnn",
      "Happy Days": "nnynynynnnynynnnnnnnnnnsnnn",
      "Everybody Loves Raymond": "nnnyynynnnnnnnnnnnnnynnnnnn",
      "Family Matters": "nnnnyyynnnnnsynnnnnnnnnnynn",
      "Parks and Recreation": "nnnnnnnnnnnnnnnynnnynnysnnn",
      "Dallas": "nnynynnnnnnnnnnnnnnnnynnnnn",
      "Little House on the Prairie": "nnnnynnnnnynsynnnnnnnysnnnn",
      "Magnum, P.I.": "nnnnnsnnnnnnnnynnnnnyynnnnn",
      "Miami Vice": "nnnnnynnnnnnnnysnnnnnynnynn",
      "ER": "nnynnynnnnnnnnnynnnnnynnynn",
      "Law & Order": "ynyynynnnnnnnnyynnnnnynnynn",
      "Mad Men": "nnnynnnnnnynnnnynnnnnynnynn",
      "This Is Us": "nnnnynnnnnsnnnnnnnnnnynnnnn",
      "Yellowstone": "ynnnynnnnnnnnnsnnnnnnynnnnn",
      "Succession": "nynyynnnnnnnnnnsnnnnnynnynn",
      "Doctor Who": "ynynnnnnnssynnnnysnnsynnnny",
      "Knight Rider": "nnnnnsnnnnnnnnynnnnnnynnnns",
      "Quantum Leap": "snnnnnnnnnynnnnnnnnnnynnnns",
      "Buffy the Vampire Slayer": "nnnnnnnnnynnyynnnynyyyyynnn",
      "Smallville": "nnynsnnnnynnyynnynnynynnnnn",
      "Supernatural": "nnynsnnnnsnnnnnnnynnnynnnny",
      "Westworld": "nynnnnnnnnnnnynsnnnynysnnnn",
      "The Last of Us": "yynnnnnnnnnnsynnnynnnysnnny",
      "The Flintstones": "nnnnynynnnynnnnnnnnyynnnnnn",
      "Mister Rogers' Neighborhood": "nnynnnnynnnnnnnnnnnsynnnnyn",
      "Teenage Mutant Ninja Turtles": "nnyysnnnnsnnyysnnnynnnnnynn",
      "Arthur": "nnynynnnnnnnyynnnnyyynnsnnn",
      "Gravity Falls": "nnnnsnnnnynnynnnnynynnsnnnn",
      "Dora the Explorer": "snnnnnnnnnnnynnnnnynynynnsy",
      "Phineas and Ferb": "snnnynnnnnnnynnnnnyyynnnnyn",
      "Adventure Time": "nnynnnnnnynnynnnnyyynnnsnns",
      "Jeopardy!": "ynynnnyyynnnnnnnnnnnnnnnnnn",
      "Wheel of Fortune": "ynynnnyyynnnnnnnnnnnnnnnnnn",
      "The Price Is Right": "ynynnnyyynnnnnnnnnnnnynnnnn",
      "America's Funniest Home Videos": "ynynnnyyynnnnnnnnnnnnsnnnnn",
      "The Real World": "nnysnnnnnnnnnnnnnnnnnnnnynn",
      "Who Wants to Be a Millionaire": "snynnnyyynnynnnnnnnnnsnnnnn",
      "Dancing with the Stars": "ynynnnyyynnynnnnnnnnnynnnsn",
      "The Bachelor": "ynynnnnyynnnnnnnnnnnnynnnns",
      "The Voice": "ynynnnyyynnynnnnnnnnnynnnyn"
    }
  },
  "Video Games": {
    q: [
      ["nintendo", "Is it made by Nintendo?"],
      ["arcade", "Did it start out as an arcade game?"],
      ["online", "Is it mostly played online against other people?"],
      ["human", "Is the main character a human?"],
      ["animal", "Is the main character an animal or creature?"],
      ["guns", "Does the hero carry a gun?"],
      ["space", "Is it set in outer space or on another planet?"],
      ["fantasy", "Is it set in a magical fantasy world?"],
      ["open_world", "Is it an open-world game you can roam freely?"],
      ["three_d", "Does it have 3D graphics?"],
      ["free", "Is it free to play?"],
      ["mascot", "Does it star a famous mascot character?"],
      ["phone_web", "Did it first get popular on phones or in a web browser?"],
      ["story", "Does it have a big story told with cutscenes?"],
      ["build", "Can you build or craft things in it?"],
      ["first_person", "Is it played from a first-person view?"],
      ["japanese", "Was it made by a Japanese company?"],
      ["vehicle", "Do you drive a car, kart, or motorbike?"],
      ["fight", "Do you battle enemies?"],
      ["aliens", "Are there aliens in it?"],
      ["pc_first", "Was it first made for home computers?"],
      ["money", "Do you manage money or a budget?"],
      ["controller", "Does it use a special controller or body movement?"],
      ["couch", "Is it best played with friends in the same room?"],
      ["mature", "Is it rated M for mature players?"],
      ["indie", "Was it made by a tiny team or a single person?"],
      ["songs", "Does it feature real hit songs?"]
    ],
    a: {
      "Minecraft": "nnsynnnyyynnnnysnnsnynnnnyn",
      "Super Mario Bros.": "ynnynnnynnnynnnnynynnnnnnnn",
      "Tetris": "nnnnnnnnnnnnnnnnnnnnynnnnsn",
      "Fortnite": "nnyynynssyynnnynnnyssnnnnns",
      "Pac-Man": "nynnsnnnnnnynnnnynsnnnnnnnn",
      "The Legend of Zelda": "ynnynnnyysnynnnnynynnnnnnnn",
      "Pokémon": "ynnyynnyssnynsnnynynnsnnnnn",
      "Grand Theft Auto V": "nnsynynnyynnnynnnyynnsnnyny",
      "Mario Kart": "ynsssnnsnsnynnnnyysnnnnynnn",
      "Call of Duty": "nnyynynnnysnnynynnynynnnynn",
      "Among Us": "nnysnnynnnsnynnnnnsssnnsnyn",
      "Roblox": "nnysnsnssyynnnynnnnnynnnnnn",
      "The Sims": "nnnynnnnnsnnnnynnnnnyynnnnn",
      "Animal Crossing: New Horizons": "ynnysnnssynnnnynynnnnynnnnn",
      "Pong": "nynnnnnnnnnnnnnnnnnnnnnynnn",
      "Halo: Combat Evolved": "nnnynyynnynsnynynsyynnnnynn",
      "Street Fighter II": "nynynnnnnnnnnnnnynynnnnsnnn",
      "Sonic the Hedgehog": "nnnnynnsnnnynnnnynynnnnnnnn",
      "Angry Birds": "nnnnynnnnnnsynnnnnynnnnnnnn",
      "Candy Crush Saga": "nnnnnnnnnnynynnnnnnnsnnnnnn",
      "Space Invaders": "nynnnnynnnnnnnnnynyynnnnnnn",
      "Asteroids": "nynnnnynnnnnnnnnnnysnnnnnnn",
      "Donkey Kong": "yynysnnnnnnynnnnynsnnnnnnnn",
      "Frogger": "nynnynnnnnnnnnnnynnnnnnnnnn",
      "Galaga": "nynnnnynnnnnnnnnynyynnnnnnn",
      "Doom": "nnnynyynnsnnnnnynnynynnnynn",
      "Mortal Kombat": "nynynnnnnnnnnnnnnnynnnnsynn",
      "Need for Speed": "nnnnnnnnnynnnnnnnynnnnnnnns",
      "Gran Turismo": "nnnnnnnnnynnnnnnyynnnnnnnnn",
      "Super Smash Bros.": "ynnssnnsnynynnnnynynnnnynnn",
      "Super Mario 64": "ynnynnnynynynsnnynynnnnnnnn",
      "Wii Sports": "ynnynnnnnynnnnnnynnnnnyynnn",
      "Guitar Hero": "nnnynnnnnynnnnnnnnnnnnyynny",
      "Portal": "nnnynnnnnynnnsnynnnnsnnnnnn",
      "The Last of Us": "nnnynynnnynnnysnnnynnnnnynn",
      "Rocket League": "nnynnnnnnyynnnnnnynnsnnsnsn",
      "Overwatch": "nnysnynnnysnnnnynnynnnnnnnn",
      "Pokémon GO": "snsyynnnsyyyynnnsnsnnnynnnn",
      "Stardew Valley": "nnnynnnssnnnnnynnnnnyynnnyn",
      "Elden Ring": "nnnynnnyyynnnssnynynnnnnynn",
      "The Oregon Trail": "nnnynnnnnnnnnnnnnnnnyynnnsn",
      "Metroid": "ynnynyynnnnsnnnnynyynnnnnnn",
      "Mega Man": "nnnnnsnnnnnynnnnynynnnnnnnn",
      "Crash Bandicoot": "nnnnynnsnynynsnnnnynnnnnnnn",
      "Final Fantasy VII": "nnnynnnynynnnynnynynnnnnnnn",
      "Hollow Knight": "nnnnynnysnnnnsnnnnynynnnnyn",
      "Galaxian": "nynnnnynnnnnnnnnynyynnnnnnn",
      "Missile Command": "nynnnnnnnnnnnnnnnnynnnsnnnn",
      "Duck Hunt": "ynnsnynnnnnnnnnsynsnnnynnnn",
      "GoldenEye 007": "snnynynnnynnnynynnynnnnynnn",
      "Gears of War": "nnnynysnnynnnynnnnynnnnnynn",
      "Apex Legends": "nnyynysnnyynnnnynnynnnnnnnn",
      "Breakout": "nynnnnnnnnnnnnnnnnnnnnnnnnn",
      "Q*bert": "nynnynnnnnnsnnnnnnsnnnnnnnn",
      "Myst": "nnnynnnynynnnsnynnnnynnnnnn",
      "Bejeweled": "nnnnnnnnnnnnynnnnnnnynnnnnn",
      "Plants vs. Zombies": "nnnsnnnnnnnnnnnnnnynynnnnnn",
      "Fruit Ninja": "nnnnnnnnnnnnynnnnnnnnnsnnnn",
      "Wordle": "nnnnnnnnnnynynnnnnnnsnnnnyn",
      "Pole Position": "nynsnnnnnsnnnnnnyynnnnsnnnn",
      "Excitebike": "ynnynnnnnnnnnnsnyynnnnnnnnn",
      "Mike Tyson's Punch-Out!!": "ynnynnnnnnnnnnnnynynnnnnnnn",
      "Tekken": "nynynnnnnynnnnnnynynnnnsnnn",
      "Crash Team Racing": "nnnnynnnnynynnnnnyssnnnynnn",
      "Burnout 3: Takedown": "nnnnnnnnnynnnnnnnysnnnnnnny",
      "Forza Horizon": "nnnnnnnnyynnnnnnnynnnnnnnny",
      "SimCity": "nnnnnnnnnnnnnnynnnnnyynnnnn",
      "RollerCoaster Tycoon": "nnnnnnnnnnnnnnynnnnnyynnnyn",
      "Zoo Tycoon": "nnnnsnnnnnnnnnynnnnnyynnnnn",
      "Nintendogs": "ynnnynnnnynnnnnnynnnnnsnnnn",
      "Spore": "nnnnynsnsynnnnynnnnyynnnnnn",
      "Terraria": "nnnynnnyynnnnnynnnynynnnnyn",
      "Goat Simulator": "nnnnynnnyynnnnnnnnnnynnnnyn",
      "Cities: Skylines": "nnnnnnnnnynnnnynnnnnyynnnsn",
      "Dance Dance Revolution": "nynsnnnnnnnnnnnnynnnnnysnns",
      "Mario Party": "ynnsnnnsnynynnnnynnnnnnynnn",
      "Tony Hawk's Pro Skater": "nnnynnnnnynnnnnnnnnnnnnnnny",
      "Wii Fit": "ynnynnnnnynnnnnnynnnnnynnnn",
      "Just Dance": "nnnynnnnnsnnnnnnnnnnnnyynny",
      "Fall Guys": "nnynsnnnnyynnnnnnnnnsnnnnnn"
    }
  },
  "Brands & Companies": {
    q: [
      ["american", "Is it an American company?"],
      ["japanese", "Is it a Japanese company?"],
      ["asian", "Is it from Asia?"],
      ["european", "Is it from Europe?"],
      ["online", "Is it mainly a website or app?"],
      ["stores", "Does it have its own stores or restaurants you can walk into?"],
      ["red_logo", "Is its logo mostly red?"],
      ["blue_logo", "Is its logo mostly blue?"],
      ["named_person", "Is it named after a real person?"],
      ["electronics", "Does it make electronic devices or computer chips?"],
      ["mascot", "Does it have a famous mascot or cartoon character?"],
      ["multiword", "Is its name two or more words?"],
      ["shoes", "Is it best known for shoes or sneakers?"],
      ["video_games", "Does it make video games or game consoles?"],
      ["fast_food", "Is it a fast-food chain?"],
      ["restaurant", "Does it run restaurants or cafes?"],
      ["social", "Is it a streaming or social media app?"],
      ["pickup", "Does it sell a pickup truck?"],
      ["parent", "Is it owned by a bigger parent company?"],
      ["california", "Is it based in California?"],
      ["movies_tv", "Does it make movies or TV shows?"],
      ["other_brands", "Does it mostly sell other companies' products?"],
      ["logo_creature", "Does its logo show an animal or a person?"],
      ["a_to_m", "Does its name start with a letter from A to M?"]
    ],
    a: {
      "Apple": "ynnnnynnnynnnnnnnnnyynny",
      "Nike": "ynnnnynnnnnnynnnnnnnnnnn",
      "McDonald's": "ynnnnysnynynnnyynnnnnnny",
      "Coca-Cola": "ynnnnnynnnssnnnnnnnnnnny",
      "Amazon": "ynnnysnnnynnnsnnnnnnyyny",
      "Google": "ynnnynnnnynnnnnnnnyynnny",
      "LEGO": "nnnynyynnnsnnnnnnnnnnnny",
      "Disney": "ynnnnynsynynnnnnnnnyynny",
      "Tesla": "ynnnnyynysnnnnnnnynsnnnn",
      "Starbucks": "ynnnnynnnnnnnnnynnnnnnyn",
      "Netflix": "ynnnynynnnnnnsnnynnyynnn",
      "IKEA": "nnnynynnsnnnnnnsnnnnnnny",
      "Toyota": "nyynnnsnynnnnnnnnynnnnnn",
      "Samsung": "nnynnsnynynnnnnnnnnnnnnn",
      "Walmart": "ynnnnynyynnnnnnnnnnnnynn",
      "Microsoft": "ynnnnnnnnynnnynnnnnnnnny",
      "Adidas": "nnnynynnynnnsnnnnnnnnnny",
      "Nintendo": "nyynnsynnyynnynnnnnnsnnn",
      "Red Bull": "nnnynnsnnnnynnnnnnnnnnyn",
      "Costco": "ynnnnynnnnnnnnnnnnnnnyny",
      "Puma": "nnnynynnnnnnsnnnnnnnnnyn",
      "Under Armour": "ynnnnynnnnnynnnnnnnnnnnn",
      "Lululemon": "nnnnnyynnnnnnnnnnnnnnnny",
      "Ford": "ynnnnnnyynnnnnnnnynnnnny",
      "Ferrari": "nnnynnnnynnnnnnnnnnnnnyy",
      "BMW": "nnnynnnsnnnnnnnnnnnnnnny",
      "Honda": "nyynnnnnynnnnnnnnynnnnny",
      "Meta": "ynnnynnynynnnsnnynnynnny",
      "YouTube": "ynnnynynnnnnnnnnynyysnnn",
      "Spotify": "nnnyynnnnnnnnnnnynnnnnnn",
      "TikTok": "nnynynnnnnnnnnnnynysnnnn",
      "Uber": "ynnnynnnnnnnnnnnnnnynnnn",
      "Airbnb": "ynnnynynnnnnnnnnnnnynnny",
      "Pepsi": "ynnnnnssnnnnnnnnnnnnnnnn",
      "Subway": "ynnnnynnnnnnnnyynnnnnnnn",
      "Chick-fil-A": "ynnnnyynnnysnnyynnnnnnsy",
      "Target": "ynnnnyynnnynnnnnnnnnnynn",
      "Mattel": "ynnnnnynsnsnnnnnnnnysnny",
      "Sony": "nyynnsnnnynnnynnnnnnynnn",
      "Domino's": "ynnnnyssnnnnnnyynnnnnnny",
      "IBM": "ynnnnnnynynnnnnnnnnnnnny",
      "Intel": "ynnnnnnynynnnnnnnnnynnny",
      "Nvidia": "ynnnnnnnnynnnnnnnnnynnnn",
      "Instagram": "ynnnynnnnnnnnnnnynyynnny",
      "Snapchat": "ynnnynnnnssnnnnnynnynnnn",
      "Hershey's": "ynnnnsnnynnnnnnnnnnnnnny",
      "Kellogg's": "ynnnnnynynynnnnnnnynnnny",
      "Krispy Kreme": "ynnnnysnnnnynnsynnnnnnny",
      "Taco Bell": "ynnnnynnynsynnyynnyynnnn",
      "Wendy's": "ynnnnyynynynnnyynnnnnnyn",
      "Chipotle": "ynnnnyynnnnnnnsynnnynnny",
      "Shake Shack": "ynnnnynnnnnynnsynnnnnnnn",
      "Macy's": "ynnnnyynynnnnnnnnnnnnyny",
      "Kroger": "ynnnnynyynnnnnnnnnnnnyny",
      "Home Depot": "ynnnnynnnnnynnnnnnnnnyny",
      "Best Buy": "ynnnnynnnnnynnnnnnnnnyny",
      "eBay": "ynnnynnnnnnnnnnnnnnynyny",
      "Etsy": "ynnnynnnnnnnnnnnnnnnnyny",
      "Shein": "nnynynnnnnnnnnnnnnnnnnnn",
      "Temu": "nnynynnnnnnnnnnnnnynnynn",
      "New Balance": "ynnnnynnnnnyynnnnnnnnnnn",
      "Converse": "ynnnnynnynnnynnnnnynnnny",
      "Champion": "ynnnnnssnnnnnnnnnnynnnny",
      "Vans": "ynnnnynnynnnynnnnnyynnnn",
      "Skechers": "ynnnnynynnnnynnnnnnynnnn",
      "Hoka": "snnsnnnnnnnnynnnnnysnnny",
      "Gymshark": "nnnynsnnnnnnnnnnnnnnnnyy",
      "Hasbro": "ynnnnnnnsnnnnnnnnnnnsnny",
      "Warner Bros.": "ynnnnnnsynyynsnnnnsyynnn",
      "Pixar": "ynnnnnnnnnynnnnnnnyyynnn",
      "PlayStation": "nyynnnnsnynnnynnnnysnnnn",
      "Xbox": "ynnnnnnnnynnnynnnnynnnnn",
      "Roblox": "ynnnynnnnnnnnynnnnnynnnn",
      "Chevrolet": "ynnnnnnnynnnnnnnnyynnnny",
      "Volkswagen": "nnnynnnynnnnnnnnnnnnnnnn",
      "Jeep": "ynnnnnnnnnnnnnnnnyynnnny",
      "Subaru": "nyynnnnynnnnnnnnnnnnnnnn",
      "Lamborghini": "nnnynnnnynnnnnnnnnynnnyy",
      "Hyundai": "nnynnnnynnnnnnnnnsnnnnny",
      "Rivian": "ynnnnsnnnnnnnnnnnynynnnn"
    }
  },
  Anime: {
    q: [
      ["movie", "Is it a movie (not a TV series)?"],
      ["ghibli", "Was it made by Studio Ghibli?"],
      ["manga", "Is it based on a manga?"],
      ["long", "Does it have more than 100 episodes?"],
      ["teen", "Is the main character a teenager?"],
      ["child", "Is the main character a young kid (under 13)?"],
      ["female_lead", "Is the main character a girl or woman?"],
      ["high_school", "Is it set mostly in a high school?"],
      ["mecha", "Does it have giant robots or mechs?"],
      ["powers", "Do characters have superpowers or magic abilities?"],
      ["monsters", "Does it have monsters, demons, or evil spirits?"],
      ["fantasy_world", "Is it set in a made-up fantasy world?"],
      ["swords", "Does it feature swords, ninjas, or samurai?"],
      ["tournament", "Does it have a tournament or big competition?"],
      ["time_travel", "Does it involve time travel?"],
      ["mascot", "Does it have a cute animal or creature sidekick?"],
      ["space", "Does a lot of it take place in outer space or on other planets?"],
      ["aliens", "Does it have aliens?"],
      ["romance", "Is romance a big part of the story?"],
      ["mystery", "Is solving a mystery or crime a big part of it?"],
      ["guns", "Do characters use guns?"],
      ["historical", "Is it set in the real historical past (before 1950)?"],
      ["future", "Is it set in the future?"],
      ["modern_japan", "Is it mostly set in present-day Japan?"],
      ["martial", "Is hand-to-hand fighting or martial arts a big part of it?"],
      ["transform", "Does the main character transform into another form?"],
      ["criminal", "Is the main character a criminal, outlaw, or pirate?"]
    ],
    a: {
      "Naruto": "nnyyssnnnyyyyynnnnnnnnnnysn",
      "One Piece": "nnyyynnnnysyysnynnnnsnnnssy",
      "Dragon Ball Z": "nnyynnnnnynssyynyynnnnnnyyn",
      "Attack on Titan": "nnynynnnnyyyynnnnnnnynnnnyn",
      "Death Note": "nnynynnsnsynnnnnnnnynnnynny",
      "Demon Slayer": "nnynynnnnyynynnnnnnnnynnsnn",
      "My Hero Academia": "nnyyynnynysnnynnnnnnnnnssnn",
      "Sailor Moon": "nnyyynysnyynnnyyssynnnnynyn",
      "Fullmetal Alchemist: Brotherhood": "nnynynnnnyyysnnnnnnnynnnsnn",
      "Neon Genesis Evangelion": "nnnnynnnynynnnnnnsnnsnysnnn",
      "Cowboy Bebop": "nnnnnnnnnnnnnnnyynnsynynyns",
      "Jujutsu Kaisen": "nnynynnynyynsynnnnnnnnnyynn",
      "Spy × Family": "nnynnsnnnynsnnnynnsnynnnsns",
      "Hunter × Hunter": "nnyysynnnyyynynnnnnnsnnnynn",
      "One-Punch Man": "nnynnnnnnyynnnnnnynnnnnnynn",
      "Sword Art Online": "nnnnynnnnsyyysnnnnynsnynnnn",
      "Chainsaw Man": "nnynynnnnyynnnnynnnnsnnsnyn",
      "Bleach": "nnyyynnsnyynynnsnnnnnnnyssn",
      "Haikyu!!": "nnynynnynnnnnynnnnnnnnnynnn",
      "Yu-Gi-Oh!": "nnyyynnynsynnynsnnnnnnnynnn",
      "Astro Boy": "nnyynynnnynnnnnnssnnynynnnn",
      "Speed Racer": "nnynsnnnnnnnnynnnnnnnnnnnnn",
      "Mobile Suit Gundam": "nnnnynnnynnnnnnnynnnynynnnn",
      "Doraemon": "nnyynynnnnnnnnyysnnnnnnynnn",
      "Captain Tsubasa": "nnyyssnnnnnnnynnnnnnnnnynnn",
      "Akira": "ynynynnnnynnnnnnnnnnynynnny",
      "Ranma ½": "nnyyynnynnnnnsnynnynnnnyyyn",
      "Slam Dunk": "nnyyynnynnnnnynnnnsnnnnynnn",
      "Detective Conan": "nnyyssnnnnnnnnnnnnnysnnynsn",
      "Gintama": "nnyynnnnnnnsynnssynnnsnnsnn",
      "Ouran High School Host Club": "nnynynyynnnnnnnnnnynnnnynnn",
      "Code Geass": "nnnnynnyyynnnnnnnnsnynsnnny",
      "Steins;Gate": "nnnnsnnnnnnnnnynnnsssnnynnn",
      "Kuroko's Basketball": "nnynynnynsnnnynnnnnnnnnynnn",
      "Tokyo Ghoul": "nnynsnnnnyynnnnnnnnnnnnysyn",
      "Mob Psycho 100": "nnynynnnnyynnnnsnnnnnnnynnn",
      "Kaguya-sama: Love Is War": "nnynynsynnnnnnnnnnynnnnynnn",
      "Blue Lock": "nnynynnnnnnnnynnnnnnnnnynnn",
      "Frieren: Beyond Journey's End": "nnynnnynnyyysynnnnnnnnnnnnn",
      "Dandadan": "nnynynsynyynnnnnnyynnnnynsn",
      "Pokémon": "nnnynynnnnyynynynnnnnnnnnnn",
      "Inuyasha": "nnyyynsnnyynynyynnynnynsnnn",
      "Yu Yu Hakusho": "nnyyynnnnyynsynsnnnnnnnyynn",
      "Saint Seiya": "nnyyynnnnynsnynnnnnnnnnsynn",
      "JoJo's Bizarre Adventure": "nnyysnnnnyynnnnnnnnnsynnynn",
      "Howl's Moving Castle": "yynnsnynnysynnnsnnynnnnnnyn",
      "Princess Mononoke": "yynnynnnnnysynnsnnsnyynnnnn",
      "Space Battleship Yamato": "nnnnsnnnnnnnnnnnyynnynynnnn",
      "Science Ninja Team Gatchaman": "nnnnsnnnysnnnnnnnsnnsnnnyyn",
      "The Super Dimension Fortress Macross": "nnnnynnnynnnnnnnyyynynynnnn",
      "Castle in the Sky": "yynnssnnsnnsnnnnnnnnynnnnnn",
      "Ghost in the Shell": "ynynnnynnsnnnnnnnnnyynynynn",
      "Trigun": "nnynnnnnnnnnnnnnynnnynynnny",
      "Digimon Adventure": "nnnnnynnnnyynnnynnnnnnnnnsn",
      "Gurren Lagann": "nnnnynnnynnsnnnnyysnsnynnnn",
      "Dr. Stone": "nnynynnnnnnnnynnsnnnnnynnnn",
      "Grave of the Fireflies": "yynnynnnnnnnnnnnnnnnnynnnnn",
      "Serial Experiments Lain": "nnnnynynnnnnnnnnnnnynnsynnn",
      "Monster": "nnynnnnnnnnnnnnnnnnyynnnnnn",
      "Psycho-Pass": "nnnnnnynnnnnnnnnnnnyynynnnn",
      "Parasyte": "nnynynnynnynnnnnnynnnnnynsn",
      "Erased": "nnynnsnnnnnnnnynnnnynnnynnn",
      "The Promised Neverland": "nnynnyynnnysnnnnnnnsnnsnnnn",
      "Vinland Saga": "nnynssnnnnnnynnnnnnnnynnsns",
      "Lupin the Third": "nnyynnnnnnnnynnnnnssynnnnny",
      "Urusei Yatsura": "nnyyynnynynnnnnnnyynnnnynnn",
      "My Neighbor Totoro": "yynnnyynnnnnnnnynnnnnnnsnnn",
      "Kiki's Delivery Service": "yynnynynnynsnnnynnnnnnnnnnn",
      "Crayon Shin-chan": "nnyynynnnnnnnnnnnnnnnnnynnn",
      "Azumanga Daioh": "nnynynyynnnnnnnnnnnnnnnynnn",
      "Fruits Basket": "nnynynyynnnnnnnsnnynnnnynyn",
      "K-On!": "nnynynyynnnnnnnnnnnnnnnynnn",
      "Toradora!": "nnnnynsynnnnnnnnnnynnnnynnn",
      "The Melancholy of Haruhi Suzumiya": "nnnnynsynynnnnynnynsnnnynnn",
      "Ashita no Joe": "nnynynnnnnnnnynnnnnnnnnyyns",
      "Initial D": "nnynynnsnnnnnynnnnnnnnnynnn",
      "The Prince of Tennis": "nnyyssnnnnnnnynnnnnnnnnynnn",
      "Hajime no Ippo": "nnyyynnnnnnnnynnnnnnnnnyynn",
      "Free!": "nnnnynnynnnnnynnnnnnnnnynnn",
      "Yuri!!! on Ice": "nnnnnnnnnnnnnynnnnsnnnnsnnn"
    }
  }
};

// Questions built from catalog tags and years. tags: { tag: "question" }, years: [cutoffs, "question with {y}"].
window.AUTOQ = {
  Celebrities: { tags: { music: "Are they mainly known for music?", acting: "Are they mainly known for acting or TV?", sports: "Are they mainly known for sports?" } },
  Places: { tags: { north_america: "Is it in North America?", south_america: "Is it in South America?", europe: "Is it in Europe?", asia: "Is it in Asia?", africa: "Is it in Africa?", oceania: "Is it in Oceania or Antarctica?", natural: "Is it a natural wonder?", landmark: "Is it a man-made landmark?", city: "Is it a city or region?" } },
  Movies: { tags: { animated: "Is it animated?", action: "Is it an action or sci-fi movie?", drama: "Is it a drama?", comedy: "Is it a comedy?" }, years: [[1980, 1990, 2000, 2010], "Did it come out before {y}?"] },
  Songs: { tags: { rock: "Is it a rock song?", pop: "Is it a pop song?", rnb: "Is it R&B or soul?", hiphop: "Is it hip-hop or Latin?" }, years: [[1980, 1990, 2000, 2010], "Did it come out before {y}?"] },
  Animals: { tags: { mammal: "Is it a mammal?", bird: "Is it a bird?", sea: "Is it sea life?", reptile: "Is it a reptile or amphibian?" } },
  Foods: { tags: { breakfast: "Is it a breakfast food?", mains: "Is it a main dish?", snacks: "Is it a snack?", desserts: "Is it a dessert?", american: "Is it American food?", italian: "Is it Italian food?", asian: "Is it Asian food?", mexican: "Is it Mexican food?", european: "Is it European food?" } },
  "TV Shows": { tags: { comedy: "Is it a comedy?", drama: "Is it a drama?", scifi: "Is it sci-fi or fantasy?", animated: "Is it animated or a kids' show?", reality: "Is it a reality, game or talk show?" }, years: [[1980, 1990, 2000, 2010], "Did it first air before {y}?"] },
  "Video Games": { tags: { adventure: "Is it an adventure game or platformer?", shooter: "Is it a shooter?", puzzle: "Is it a puzzle game?", racing: "Is it a racing or fighting game?", sandbox: "Is it a sandbox or life sim?", party: "Is it a party or social game?" }, years: [[1980, 1990, 2000, 2010], "Did it come out before {y}?"] },
  "Brands & Companies": { tags: { tech: "Is it a tech company?", food: "Is it a food or drink brand?", retail: "Is it a retailer?", sportswear: "Is it a sportswear brand?", entertainment: "Is it an entertainment or toy company?", cars: "Is it a car company?" }, years: [[1900, 1950, 1980, 2000], "Was it founded before {y}?"] },
  Anime: { tags: { action: "Is it action or adventure?", scifi: "Is it sci-fi?", dark: "Is it dark or a thriller?", comedy: "Is it a comedy?", sports: "Is it about sports?" }, years: [[1980, 1990, 2000, 2010], "Did it first come out before {y}?"] }
};
